version: "3.0"
services:
  funnela:
    image: funnela/funnela-web:latest
    ports:
      - 80:80
    environment:
      - REDIS_DSN=tcp://redis:6379
      - DATABASE_HOST=db
      - DATABASE_NAME=funnela
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=PassWord
      - SECURITY_SALT=BGeUEiaRugAvCDUJTouNLoqWASCaYEUB
      - SUPERVISOR_PASSWORD=MasterPassword

  redis:
    image: redis

  db:
    image: postgres:9.6
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: PassWord
      POSTGRES_DB: funnela

  mail-daemon:
    image: funnela/funnela-mail-daemon:latest
    restart: on-failure
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=PassWord
      - DATABASE_NAME=funnela

volumes:
  pgdata:
    driver: local
